name: macOS VNC - CLOUDFLARE
on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 9999

    steps:
      - name: Install Cloudflared
        run: |
          brew install cloudflare/cloudflare/cloudflared
          echo "✅ Cloudflared Installed!"

      - name: Enable VNC/Screen Sharing
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all -allowAccessFor -allUsers
          sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false
          echo "✅ VNC Enabled!"

      - name: Set VNC Password (Legacy VNC)
        shell: bash
        run: |
          set -e
          # Ensure RemoteManagement directories exist and proper ownership
          sudo mkdir -p /Library/Preferences
          # Use kickstart with sudo to set legacy VNC password
          echo "P@ssw0rd123!" | sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all \
            -clientopts -setvnclegacy -vnclegacy yes -setvncpw -vncpw P@ssw0rd123!
          # Also set system VNC password key (some runners require this)
          sudo /usr/libexec/PlistBuddy -c "Add :VNCLegacyPasswords array" /Library/Preferences/com.apple.RemoteManagement.plist 2>/dev/null || true
          sudo /usr/libexec/PlistBuddy -c "Delete :VNCLegacyPasswords:0" /Library/Preferences/com.apple.RemoteManagement.plist 2>/dev/null || true
          HASH=$(python3 - <<'PY'
import sys,hashlib
print(hashlib.md5(b"P@ssw0rd123!").hexdigest())
PY
)
          sudo /usr/libexec/PlistBuddy -c "Add :VNCLegacyPasswords:0 data $(echo $HASH | xxd -r -p | base64)" /Library/Preferences/com.apple.RemoteManagement.plist
          sudo launchctl unload /System/Library/LaunchDaemons/com.apple.screensharing.plist 2>/dev/null || true
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          echo "✅ VNC Password Set!"

      - name: Start Cloudflare Tunnel
        run: |
          echo "============================================"
          echo "🚀 macOS VNC - CLOUDFLARE TUNNEL"
          echo "============================================"
          echo ""
          cloudflared tunnel --url tcp://localhost:5900 > tunnel.log 2>&1 &
          sleep 15
          cat tunnel.log | grep -o 'https://[^[:space:]]*trycloudflare.com' || echo "Check logs for tunnel URL"
          echo ""
          echo "✅ TUNNEL STARTED!"
          echo ""
          echo "📋 CONNECTION DETAILS:"
          echo "   PASSWORD: P@ssw0rd123!"
          echo "   OS: macOS Monterey/Ventura"
          echo "   Architecture: $(uname -m)"
          echo "============================================"

      - name: Keep Session Alive
        run: |
          echo "⏳ Session Active - Keeping alive..."
          while true; do
            sleep 60
            echo "✓ Active - $(date '+%H:%M:%S')"
          done
